# 配置mysql
[mysql]
host = 127.0.0.1
port = 13306
user = root
password = 123456
database = subjects_kg

# 配置redis
[redis]
host = localhost
port = 6379
password =1234
db = 0

# 配置milvus
[milvus]
host = localhost
port = 19530
database_name=EduRAG
collection_name=edurag_03

#llm配置
[llm]
model=qwen-plus
dashscope_api_key=sk-08ca6e2b30304868bebc8f943373b194
dashscope_base_url=https://dashscope.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size=1200
child_chunk_size=300
chunk_overlap=50
retrieval_k=3
candidate_m=2


# 配置日志
[log]
log_file =logs/app.log
